config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]

  post '/messages' => 'pointless_feedback/messages#create'

  post '/upload/create' => 'uploader#create'

  get '/admin_panel' => 'admin_panel#index', as: 'admin_panel'

  scope '/admin_panel' do
    resources :admins
    resources :dishes
    resources :categories
    resources :branches
    resources :pages do
      resources :images, :only => [:create, :destroy]
    end
    get 'sliders' => 'slider#index', as: 'sliders'
    get 'slider/:id' => 'slider#show', as: 'slider'
  end

  get '/login' => 'sessions#new', as: 'login'
  delete '/logout' => 'sessions#destroy', as: 'logout'
  root 'home#index', as: 'home'

end

app/models/branch.rb
class Branch < ActiveRecord::Base
  has_many :dishes, dependent: :destroy
  validates :name, presence: true, uniqueness: { case_sensitive: false }

  # Put all branches in a hash and group their dishes by category
  def self.group_dishes_by_category
    branches = all
    res = {}
    if branches
      branches.each do |branch|
        res[branch.name] = {}
        branch.dishes.order(:created_at).each do |dish|
          if res[branch.name][dish.category_name].nil?
            res[branch.name][dish.category_name] = [dish]
          else
            res[branch.name][dish.category_name] << dish
          end
        end
      end
    end
    res
  end

  # Get branch menu
  def group_dishes_by_category
    res = {}
    self.dishes.order(:created_at).each do |dish|
      if res[dish.category_name].nil?
        res[dish.category_name] = [dish]
      else
        res[dish.category_name] << dish
      end
    end
    res
  end
end

app/controllers/branches_controller.rb
class BranchesController < BaseController
  before_action :set_branch, only: [:show, :edit, :update, :destroy]

  # GET /branches
  # GET /branches.json
  def index
    @branches = Branch.all
  end

  # GET /branches/1
  # GET /branches/1.json
  def show
  end

  # GET /branches/new
  def new
    @branch = Branch.new
  end

  # GET /branches/1/edit
  def edit
  end

  # POST /branches
  # POST /branches.json
  def create
    @branch = Branch.new(branch_params)

    respond_to do |format|
      if @branch.save
        format.html { redirect_to branches_path, notice: 'Branch was successfully created.' }
        format.json { render :show, status: :created, location: @branch }
      else
        format.html { render :new }
        format.json { render json: @branch.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /branches/1
  # PATCH/PUT /branches/1.json
  def update
    respond_to do |format|
      if @branch.update(branch_params)
        format.html { redirect_to branches_path, notice: 'Branch was successfully updated.' }
        format.json { render :show, status: :ok, location: @branch }
      else
        format.html { render :edit }
        format.json { render json: @branch.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /branches/1
  # DELETE /branches/1.json
  def destroy
    @branch.destroy
    respond_to do |format|
      format.html { redirect_to branches_url, notice: 'Branch was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_branch
      @branch = Branch.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def branch_params
      params.require(:branch).permit(:name)
    end
end

app/helpers/branches_helper.rb
module BranchesHelper
end

app/views/branches/_form.html.erb
<%= form_for(@branch) do |f| %>
  <% if @branch.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= pluralize(@branch.errors.count, "error") %> prohibited this branch from being saved:</h2>

      <ul>
      <% @branch.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit class: "btn btn-success" %>
  </div>
<% end %>

app/views/branches/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <h1>Editing Branch</h1>

      <%= render 'form' %>
      <%= link_to 'Back', branches_path %>
    </div>
  </div>
</div>

app/views/branches/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <% if notice %>
        <p id="notice" class="alert alert-warning"><%= notice %></p>
      <% end %>

      <h1>Listing Branches</h1>

      <table class="table table-bordered table-striped">
        <thead>
          <tr>
            <th>Name</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @branches.each do |branch| %>
            <tr>
              <td><%= branch.name %></td>
              <td><%= link_to 'Edit', edit_branch_path(branch) %></td>
              <td><%= link_to 'Destroy', branch, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <br>

      <%= link_to 'New Branch', new_branch_path, class: "btn btn-primary" %>
      <%= link_to 'Back to Dishes', dishes_path %>

    </div>
  </div>
</div>

app/views/branches/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <h1>New Branch</h1>

      <%= render 'form' %>

      <%= link_to 'Back', branches_path %>
    </div>
  </div>
</div>

app/views/branches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @branch.name %>
</p>

<%= link_to 'Edit', edit_branch_path(@branch) %> |
<%= link_to 'Back', branches_path %>