config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]

  post '/messages' => 'pointless_feedback/messages#create'

  post '/upload/create' => 'uploader#create'

  get '/admin_panel' => 'admin_panel#index', as: 'admin_panel'

  scope '/admin_panel' do
    resources :admins
    resources :dishes
    resources :categories
    resources :branches
    resources :pages do
      resources :images, :only => [:create, :destroy]
    end
    get 'sliders' => 'slider#index', as: 'sliders'
    get 'slider/:id' => 'slider#show', as: 'slider'
  end

  get '/login' => 'sessions#new', as: 'login'
  delete '/logout' => 'sessions#destroy', as: 'logout'
  root 'home#index', as: 'home'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  has_secure_password
  validates :username, presence: true, uniqueness: true
end

app/models/branch.rb
class Branch < ActiveRecord::Base
  has_many :dishes, dependent: :destroy
  validates :name, presence: true, uniqueness: { case_sensitive: false }

  # Put all branches in a hash and group their dishes by category
  def self.group_dishes_by_category
    branches = all
    res = {}
    if branches
      branches.each do |branch|
        res[branch.name] = {}
        branch.dishes.order(:created_at).each do |dish|
          if res[branch.name][dish.category_name].nil?
            res[branch.name][dish.category_name] = [dish]
          else
            res[branch.name][dish.category_name] << dish
          end
        end
      end
    end
    res
  end

  # Get branch menu
  def group_dishes_by_category
    res = {}
    self.dishes.order(:created_at).each do |dish|
      if res[dish.category_name].nil?
        res[dish.category_name] = [dish]
      else
        res[dish.category_name] << dish
      end
    end
    res
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :dishes, dependent: :destroy
  validates :name, presence: true, uniqueness: { case_sensitive: false }
end

app/models/dish.rb
class Dish < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  belongs_to :category
  belongs_to :branch

  validates :name, presence: true
  validates_presence_of :price, :category, :branch
  validate :special_dish, on: :create

  def special_dish
    if self.special == true
      validates_presence_of :image
      validates_presence_of :description
    end
  end

  def category_name
    self.category.name if self.category
  end

  def branch_name
    self.branch.name if self.branch
  end

  # Special dishes
  def self.special_dishes
    return where(special: true)
  end
end

app/models/page.rb
class Page < ActiveRecord::Base
  PAGES = %w(main_top main_bottom specials about gallery menu contact_us phone email address info map)
  #serialize :images
  mount_uploaders :images, PageImagesUploader
  validates :page, presence: true, uniqueness: { case_sensitive: false }

  # All pages in a hash
  def self.pages
    pages = {}
    Page.all.each do |page|
      pages[page.page] = page
    end
    pages
  end
end

app/controllers/base_controller.rb
class BaseController < ApplicationController
  before_action :ensure_login
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :ensure_login
  before_action :menu, :specials, :pages
  helper_method :hyphenate

  def index
    @message = PointlessFeedback::Message.new
  end

  private
    def menu
      @branches = Branch.group_dishes_by_category
    end

    def specials
      @specials = Dish.special_dishes
    end

    def pages
      @pages = Page.pages
    end

    def hyphenate(string)
      string.downcase.gsub(/\s+/, "-")
    end
end

app/controllers/pages_controller.rb
class PagesController < BaseController
  before_action :set_page, only: [:show, :edit, :update, :destroy]

  # GET /pages
  # GET /pages.json
  def index
    @pages = Page.all
  end

  # GET /pages/1
  # GET /pages/1.json
  def show
  end

  # GET /pages/new
  def new
    @page = Page.new
  end

  # GET /pages/1/edit
  def edit
  end

  # POST /pages
  # POST /pages.json
  def create
    @page = Page.new(page_params)

    respond_to do |format|
      if @page.save
        format.html { redirect_to @page, notice: 'Page was successfully created.' }
        format.json { render :show, status: :created, location: @page }
      else
        format.html { render :new }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pages/1
  # PATCH/PUT /pages/1.json
  def update
    respond_to do |format|
      if @page.update(page_params)
        format.html { redirect_to @page, notice: 'Page was successfully updated.' }
        format.json { render :show, status: :ok, location: @page }
      else
        format.html { render :edit }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1
  # DELETE /pages/1.json
  def destroy
    page_images_dir = @page.id
    @page.destroy
    if @page.images.first
      FileUtils.remove_dir("#{Rails.root}/public/uploads/page/images/#{page_images_dir}")
    end
    respond_to do |format|
      format.html { redirect_to pages_url, notice: 'Page was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_page
      @page = Page.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def page_params
      params.require(:page).permit(:page, :title, :text, { images: [] })
    end
end

app/helpers/admin_panel_helper.rb
module AdminPanelHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/base_helper.rb
module BaseHelper
end

app/helpers/branches_helper.rb
module BranchesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/slider_helper.rb
module SliderHelper
end

app/views/admins/_form.html.erb
<%= form_for(@admin) do |f| %>
  <% if @admin.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= pluralize(@admin.errors.count, "error") %> prohibited this admin from being saved:</h2>

      <ul>
      <% @admin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :username %><br>
    <%= f.text_field :username, class: "form-control" %>
  </div>
  <div class="field form-group">
    <%= f.label :password %><br>
    <%= f.password_field :password, class: "form-control" %>
  </div>
  <div class="field form-group">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/admins/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <h1>Editing Admin</h1>

      <%= render 'form' %>

      <%= link_to 'Back', admins_path %>
    </div>
  </div>
</div>

app/views/admins/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <% if notice %>
        <p id="notice" class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p id="notice" class="alert alert-danger"><%= alert %></p>
      <% end %>

      <h1>Listing Admins</h1>

      <table class="table table-bordered table-striped">
        <thead>
          <tr>
            <th>Username</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @admins.each do |admin| %>
            <% if admin.username != "master_admin" %>
              <tr>
                <td><%= admin.username %></td>
                <% if admin == current_admin %>
                <td><%= link_to 'Edit', edit_admin_path(admin) %></td>
                <% else %>
                <td></td>
                <% end %>
                <td><%= link_to 'Destroy', admin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>

      <br>

      <%= link_to 'New Admin', new_admin_path, class: "btn btn-primary" %>
      <br><br>
      <%= link_to 'Back to Panel', admin_panel_path %>
    </div>
  </div>
</div>

app/views/admins/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <h1>New Admin</h1>

      <%= render 'form' %>

      <%= link_to 'Back', admins_path %>
    </div>
  </div>
</div>

app/views/admins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @admin.username %>
</p>

<%= link_to 'Edit', edit_admin_path(@admin) %> |
<%= link_to 'Back', admins_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Krados</title>
  <meta name="viewport" content="width=device-width initial-scale=1">
  <%= favicon_link_tag 'favicon.png', rel: 'icon', type: 'image/png' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>
  <link href="https://fonts.googleapis.com/css?family=Niconne" rel="stylesheet">
  <%= csrf_meta_tags %>
</head>
<body>
  <% if logged_in? %>
    <div id="admin-bar">
      <div class="container">
        <span class="admin-info">Logged in as Admin: <%= current_admin.username %></span>
        <div class="pull-right">
          <%= link_to_unless_current "Admin Panel", admin_panel_url, class: "btn btn-default" %>
          <%= link_to_unless_current "Home Page", home_url, class: "btn btn-default" %>
          <%= link_to "Logout", logout_path, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>
        </div>
      </div>
    </div>
  <% end %>

  <%= yield %>

</body>
</html>

app/views/pages/_form.html.erb
<%= form_for(@page) do |f| %>
  <% if @page.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% @page.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :page %><br>
    <%= f.select :page, Page::PAGES.map { |p| [p, p] }, { include_blank: true }, class: "form-control" %>
  </div>
  <div class="field form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="field form-group">
    <%= f.label :text %><br>
    <%= f.text_area :text, class: "form-control", rows: "15" %>
  </div>
  <div class="field form-group">
    <%= f.label :images %>
    <%= f.file_field :images, multiple: true, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>
<br>

app/views/pages/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <h1>Editing Page</h1>

      <%= render 'form' %>

      <%= link_to 'Show', @page, class: "btn btn-primary" %> |
      <%= link_to 'Back', pages_path %>
    </div>
  </div>
</div>

app/views/pages/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <% if notice %>
      <p id="notice" class="alert alert-warning"><%= notice %></p>
      <% end %>

      <h1>Listing Pages</h1>

      <table class="table table-bordered table-striped">
        <thead>
          <tr>
            <th>Page</th>
            <th>Title</th>
            <th>Text</th>
            <th>Images</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @pages.each do |page| %>
            <tr>
              <td><%= page.page %></td>
              <td><%= page.title %></td>
              <td><%= page.text %></td>
              <td>
              <% page.images.each do |image| %>
                <%= image_tag(image.url, class: "img-thumbnail", width: "50") %>
              <% end %>
              </td>
              <td><%= link_to 'Show', page %></td>
              <td><%= link_to 'Edit', edit_page_path(page) %></td>
              <td><%= link_to 'Destroy', page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <br>

      <%= link_to 'New Page', new_page_path, class: "btn btn-primary" %>
      <br><br>
      <%= link_to 'Back to Panel', admin_panel_path %>
    </div>
  </div>
</div>

app/views/pages/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <h1>New Page</h1>

      <%= render 'form' %>

      <%= link_to 'Back', pages_path %>
    </div>
  </div>
</div>

app/views/pages/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <% if notice %>
      <p id="notice" class="alert alert-warning"><%= notice %></p>
      <% end %>

      <p>
        <strong>Page:</strong>
        <%= @page.page %>
      </p>

      <p>
        <strong>Title:</strong>
        <%= @page.title %>
      </p>

      <p>
        <strong>Text:</strong>
        <%= @page.text %>
      </p>

      <p>
        <strong>Images:</strong>
        <ul>
        <% @page.images.each_with_index do |image, index| %>
          <li>
            <%= image_tag(image.url, width: "70") %> |
            <%= link_to "Destroy", page_image_path(@page, index), method: :delete, data: { confirm: "Are you sure?" } %>
          </li>
        <% end %>
        </ul>
      </p>

      <h1>Add Images</h1>
      <%= form_for(@page, url: page_images_path(@page), method: :post) do |f| %>
        <div class="field form-group">
          <%= f.label :images %>
          <%= f.file_field :images, multiple: true, class: "form-control" %>
        </div>
        <div class="actions">
          <%= f.submit "Add More Images", class: "btn btn-primary" %>
        </div>
      <% end %>
      <br><br>

      <%= link_to 'Edit', edit_page_path(@page), class: "btn btn-primary" %> |
      <%= link_to 'Back', pages_path %>
    </div>
  </div>
</div>

app/views/pointless_feedback/messages/new.html.erb
<% if PointlessFeedback.using_captcha? %>
  <head>
    <script src='https://www.google.com/recaptcha/api.js'></script>
  </head>
<% end %>

<%= form_for @message do |f| %>
  <% if @message.errors.any? %>
    <div class="error_messages">
      <h2>
        <%= I18n.t('activerecord.errors.header', :default => 'Invalid Fields') %>
      </h2>

      <p>
        <%= I18n.t('activerecord.errors.message', :default => 'Correct the following errors and try again.') %>
      </p>

      <ul>
        <% @message.errors.full_messages.each do |message| %>
          <li><%= message.html_safe %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset class="user-fields">
    <legend>About You</legend>

    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>

    <div class="field">
      <%= f.label :email_address %>
      <%= f.text_field :email_address %>
    </div>
  </fieldset>

  <fieldset class="feedback-fields">
    <legend>Leave Your Feedback</legend>

    <div class="field">
      <%= f.label :topic %>
      <%= f.select :topic, PointlessFeedback.message_topics, { :prompt => true } %>
    </div>

    <div class="field">
      <%= f.label :description %>
      <%= f.text_area :description %>
    </div>

    <!-- This is a honeypot field to keep the spammers away. Do not remove. -->
    <!-- If this field is filled in, feedback will not be emailed -->
    <div class="contact-input" style="position: absolute; left: -9999px;">
      <%= f.text_field :contact_info %>
    </div>
    <!-- End of honeypot field -->

  </fieldset>

  <% if PointlessFeedback.using_captcha? %>
    <div class="g-recaptcha" data-sitekey="<%= PointlessFeedback.google_captcha_site_key %>"></div>
  <% end %>

  <%= f.submit 'Submit' %>
<% end %>