config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]

  post '/messages' => 'pointless_feedback/messages#create'

  post '/upload/create' => 'uploader#create'

  get '/admin_panel' => 'admin_panel#index', as: 'admin_panel'

  scope '/admin_panel' do
    resources :admins
    resources :dishes
    resources :categories
    resources :branches
    resources :pages do
      resources :images, :only => [:create, :destroy]
    end
    get 'sliders' => 'slider#index', as: 'sliders'
    get 'slider/:id' => 'slider#show', as: 'slider'
  end

  get '/login' => 'sessions#new', as: 'login'
  delete '/logout' => 'sessions#destroy', as: 'logout'
  root 'home#index', as: 'home'

end

app/controllers/admin_panel_controller.rb
class AdminPanelController < BaseController
  def index
  end
end

app/helpers/admin_panel_helper.rb
module AdminPanelHelper
end

app/views/admin_panel/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <% if notice %>
        <p id="notice" class="alert alert-success"><%= notice %></p>
      <% end %>
      <h1 class="page-header text-center"><span class="pull-left glyphicon glyphicon-user"></span>Hello <%= current_admin.username %></h1>
      <div class="admin-content">
        <h3 class="text-center">Manage Sections</h3>
        <ul class="list-group">
          <li class="list-group-item"><%= link_to "Dishes", dishes_path, class: "btn btn-primary btn-block" %></li>
          <li class="list-group-item"><%= link_to "Pages", pages_path, class: "btn btn-primary btn-block" %></li>
          <li class="list-group-item"><%= link_to "Admins", admins_path, class: "btn btn-primary btn-block" %></li>
          <li class="list-group-item"><%= link_to "Sliders", sliders_path, class: "btn btn-primary btn-block" %></li>
        </ul>
      </div>
    </div>
  </div>
</div>