config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]

  post '/messages' => 'pointless_feedback/messages#create'

  post '/upload/create' => 'uploader#create'

  get '/admin_panel' => 'admin_panel#index', as: 'admin_panel'

  scope '/admin_panel' do
    resources :admins
    resources :dishes
    resources :categories
    resources :branches
    resources :pages do
      resources :images, :only => [:create, :destroy]
    end
    get 'sliders' => 'slider#index', as: 'sliders'
    get 'slider/:id' => 'slider#show', as: 'slider'
  end

  get '/login' => 'sessions#new', as: 'login'
  delete '/logout' => 'sessions#destroy', as: 'logout'
  root 'home#index', as: 'home'

end

app/models/dish.rb
class Dish < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  belongs_to :category
  belongs_to :branch

  validates :name, presence: true
  validates_presence_of :price, :category, :branch
  validate :special_dish, on: :create

  def special_dish
    if self.special == true
      validates_presence_of :image
      validates_presence_of :description
    end
  end

  def category_name
    self.category.name if self.category
  end

  def branch_name
    self.branch.name if self.branch
  end

  # Special dishes
  def self.special_dishes
    return where(special: true)
  end
end

app/controllers/dishes_controller.rb
class DishesController < BaseController
  before_action :set_dish, only: [:show, :edit, :update, :destroy]

  # GET /dishes
  # GET /dishes.json
  def index
    @dishes = Dish.order('created_at')
  end

  # GET /dishes/1
  # GET /dishes/1.json
  def show
  end

  # GET /dishes/new
  def new
    @dish = Dish.new
  end

  # GET /dishes/1/edit
  def edit
  end

  # POST /dishes
  # POST /dishes.json
  def create
    @dish = Dish.new(dish_params)

    respond_to do |format|
      if @dish.save
        format.html { redirect_to @dish, notice: 'Dish was successfully created.' }
        format.json { render :show, status: :created, location: @dish }
      else
        format.html { render :new }
        format.json { render json: @dish.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dishes/1
  # PATCH/PUT /dishes/1.json
  def update
    respond_to do |format|
      if @dish.update(dish_params)
        format.html { redirect_to @dish, notice: 'Dish was successfully updated.' }
        format.json { render :show, status: :ok, location: @dish }
      else
        format.html { render :edit }
        format.json { render json: @dish.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dishes/1
  # DELETE /dishes/1.json
  def destroy
    dish_image_dir = @dish.id
    @dish.destroy
    unless @dish.image.file.nil?
      FileUtils.remove_dir("#{Rails.root}/public/uploads/dish/image/#{dish_image_dir}")
    end
    respond_to do |format|
      format.html { redirect_to dishes_url, notice: 'Dish was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dish
      @dish = Dish.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dish_params
      params.require(:dish).permit(:name, :price, :description, :image, :special, :show_description, :category_id, :branch_id)
    end
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/views/dishes/_form.html.erb
<%= form_for(@dish, html: { multipart: true }) do |f| %>
  <% if @dish.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= pluralize(@dish.errors.count, "error") %> prohibited this dish from being saved:</h2>

      <ul>
      <% @dish.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="field form-group">
    <%= f.label :price %><br>
    <%= f.number_field :price, class: "form-control" %>
  </div>
  <div class="field form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: "form-control", rows: "4" %>
  </div>
  <div class="field form-group">
    <%= f.label :image %><br>
    <% if @dish.image.file.nil? %>
    <%= f.file_field :image, class: "form-control" %>
    <% else %>
    <%= f.file_field :image, class: "form-control" %>
    <p class="help-block">Current Image: <%= @dish.image.file.filename %> <%= image_tag(@dish.image_url, width: "70", class: "img-thumbnail") %></p>
    <% end %>
  </div>
  <div class="field checkboxes slideThree">
    <%= f.label :special %><br>
    <%= f.check_box :special %>
  </div>
  <div class="field checkboxes slideThree">
    <%= f.label :show_description %><br>
    <%= f.check_box :show_description %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.select :category_id, Category.all.collect { |c| [c.name, c.id] }, { include_blank: true }, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :branch %><br>
    <%= f.select :branch_id, Branch.all.collect { |b| [b.name, b.id] }, { include_blank: true }, class: "form-control" %>
  </div><br>
  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/dishes/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <h1>Editing Dish</h1>

      <%= render 'form' %>

      <%= link_to 'Show', @dish %> |
      <%= link_to 'Back', dishes_path %>
      <br><br>
    </div>
  </div>
</div>

app/views/dishes/index.html.erb
<% if notice %>
  <p id="notice" class="alert alert-success"><%= notice %></p>
<% end %>

<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <div class="head-dishes">
        <h1>Listing Dishes</h1>
        <div class="file-upload">
          <%= form_tag '/upload/create', { :multipart => true, class: 'menuForm' } do %>
            <%= file_field_tag 'menu', class: 'inputfile' %>
            <%= button_tag "Upload Menu", { type: 'button', class: 'uploadButton btn btn-primary' } %>
          <% end %>
        </div>
      </div>
      <table class="table table-bordered table-striped">
        <thead>
          <tr>
            <th>Name</th>
            <th>Price</th>
            <!-- <th>Description</th> -->
            <th>Image</th>
            <th>Special</th>
            <th>Category</th>
            <th>Branch</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @dishes.each do |dish| %>
            <tr>
              <td><%= dish.name %></td>
              <td><%= dish.price %></td>
              <!-- <td><%= dish.description %></td> -->
              <td>
                <% if dish.image.file %>
                <%= image_tag(dish.image_url, size: "50x50", alt: "Dish Photo", class: "img-thumbnail") %>
                <% end %>
              </td>
              <td><%= dish.special ? "Yes" : "No" %></td>
              <td><%= dish.category_name %></td>
              <td><%= dish.branch_name %></td>
              <td><%= link_to 'Show', dish %></td>
              <td><%= link_to 'Edit', edit_dish_path(dish) %></td>
              <td><%= link_to 'Destroy', dish, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <br>

      <%= link_to 'New Dish', new_dish_path, class: "btn btn-primary" %>
      <%= link_to 'Categories', categories_path, class: "btn btn-success" %>
      <%= link_to 'Branches', branches_path, class: "btn btn-danger" %>
      <br><br>
      <%= link_to 'Back to Panel', admin_panel_path %>
    </div>
  </div>
</div>

app/views/dishes/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <h1>New Dish</h1>

      <%= render 'form' %>

      <%= link_to 'Back', dishes_path %>
      <br><br>
    </div>
  </div>
</div>

app/views/dishes/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <% if notice %>
        <p id="notice" class="alert alert-warning"><%= notice %></p>
      <% end %>
      <h1>Dish</h1>
      <p>
        <strong>Name:</strong>
        <%= @dish.name %>
      </p>

      <p>
        <strong>Price:</strong>
        <%= @dish.price %>
      </p>

      <p>
        <strong>Description:</strong>
        <%= @dish.description %>
      </p>

      <% if @dish.image.file %>
      <p>
        <strong>Image:</strong>
        <%= image_tag(@dish.image_url, alt: "Dish Image", width: "200") %>
      </p>
      <% end %>

      <p>
        <strong>Special:</strong>
        <%= @dish.special %>
      </p>

      <p>
        <strong>Show Description:</strong>
        <%= @dish.show_description %>
      </p>

      <p>
        <strong>Category:</strong>
        <%= @dish.category_name %>
      </p>

      <p>
        <strong>Branch:</strong>
        <%= @dish.branch_name %>
      </p>

      <%= link_to 'Edit', edit_dish_path(@dish) %> |
      <%= link_to 'Back', dishes_path %>
    </div>
  </div>
</div>